name: 'AWS ECR Docker Login'
author: 'Lars Gohr'
branding:
  icon: 'log-in'
  color: 'orange'
description: 'Logs into ECR and provides Docker credentials'
inputs:
  access_key:
    description: 'The AWS access key'
    required: true
  secret_access_key:
    description: 'The AWS secret access key'
    required: true
  region:
    description: 'The AWS region you would like to login to'
    required: true
outputs:
  username:
    description: 'The username for logging in'
    value: ${{ steps.ecr-login.outputs.username }}
  password:
    description: 'The password for logging in'
    value: ${{ steps.ecr-login.outputs.password }}
  registry:
    description: 'The registry to log in to'
    value: ${{ steps.ecr-login.outputs.registry }}
  docker_name:
    description: 'The name of the docker image'
    value: ${{ steps.ecr-login.outputs.docker_name }}

runs:
  using: 'composite'
  steps:      
    - id: ecr-login
      run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_ACCESS_KEY: ${{ inputs.access_key }}
        INPUT_SECRET_ACCESS_KEY: ${{ inputs.secret_access_key }}
        INPUT_REGION: ${{ inputs.region }}
        
