name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      # Run the build script which populates the ./dist folder
      - name: build
        run: |
          yarn
          yarn run build

      # Merge ./dist into the 'gh-pages' branch (dist in this case)
      - name: update dist branch
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: dist
          PUBLISH_DIR: ./dist

      # Check out the new branch
      - name: checkout dist
        uses: actions/checkout@master
        with:
          ref: dist

      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@release

      # Upload to S3
      - name: sync s3
        uses: jakejarvis/s3-sync-action@2fb81a9e9fea11e078587911c27754e42e6a6e88
        with:
          args: --exclude '.git*/*' --delete --follow-symlinks
        env:
          SOURCE_DIR: "./"
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Invalidate CloudFront (this action)
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/index.html"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
